
site_name: Orca 0.5.4-dev0
nav:
  - Home: index.md
#  - Concepts: concepts.md
#  - Commands: commands.md
  - Tasks: tasks.md
  - Store: store.md
#  - Examples: examples.md
#  - Workflow Reference: workflow.md
#  - API Reference: api.md
#  - About: about.md

theme: readthedocs